name: pathly-backend

include:
  - ./services/auth/compose.local.yaml
  - ./services/learning-paths/compose.local.yaml

services:
  reverse-proxy:
    build:
      context: ./services/reverse-proxy
      target: dev
    volumes:
      - type: bind
        source: ./services/reverse-proxy/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 4000:80
    depends_on:
      learning-paths:
        condition: service_healthy
      auth:
        condition: service_healthy
        restart: true
    restart: always