name: pathly

services:
  db:
    image: postgres:18-alpine
    env_file:
      - path: ./services/db/.env.example
        required: true
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD', 'pg_isready']
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - 5432:5432
  graph-db:
    image: neo4j:latest
    volumes:
      - graph-db-data:/data
    env_file:
      - path: ./services/graph-db/.env.example
        required: true
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p zaq1@WSX 'RETURN 1;'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  auth:
      build:
        context: ./services/auth
        target: dev
      env_file:
        - path: ./services/auth/.env.example
          required: true
      volumes:
        - type: bind
          source: ./services/auth/realm-export.json
          target: /opt/keycloak/data/import/realm-export.json
        - auth-data:/opt/keycloak/data
      healthcheck:
        test:
          - CMD-SHELL
          - > 
            bash -c '
              exec 3<>/dev/tcp/localhost/9000;
              printf "GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3;
              read -r data <&3;
              status=$${data:8:4};
              [ "$$status" -lt 400 ]
            '
        interval: 10s
        timeout: 15s
        retries: 3
        start_period: 60s
      ports:
        - 8080:8080
  api:
    build:
      context: ./services/api
      target: dev
    env_file:
      - path: ./services/api/.env
        required: false
      - path: ./services/api/.env.example
        required: true
    volumes:
      - ./services/api/src:/usr/src/app/services/api/src
      - ./services/api/test:/usr/src/app/services/api/test
      - type: bind
        source: ./services/api/tsconfig.json
        target: /usr/src/app/services/api/tsconfig.json
      - type: bind
        source: ./services/api/jest.config.ts
        target: /usr/src/app/services/api/jest.config.ts
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'node', 'healthcheck.js']
      timeout: 10s
      start_period: 15s
    ports:
      - 3000:3000
  reverse-proxy:
    build:
      context: ./services/reverse-proxy
    volumes:
      - type: bind
        source: ./services/reverse-proxy/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    ports:
      - 4000:80
    depends_on:
      api:
        condition: service_healthy
    restart: always
volumes:
  db-data:
  graph-db-data:
  auth-data: