name: pathly-backend

include:
  - ./infra/auth/compose.yaml
  - ./services/learning-paths/compose.yaml
  - ./services/progress/compose.yaml

services:
  reverse-proxy:
    build:
      context: ./infra/reverse-proxy
      target: dev
    env_file:
      - ./infra/reverse-proxy/.env
    volumes:
      - type: bind
        source: ./infra/reverse-proxy/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 4000:80
    depends_on:
      api-gateway:
        condition: service_healthy
      auth:
        condition: service_healthy
        restart: true
    restart: always
  api-gateway:
    build:
      context: .
      target: dev
      dockerfile: ./services/api-gateway/Dockerfile
    env_file:
      - ./services/api-gateway/.env
    volumes:
      - ./services/api-gateway/src:/usr/src/app/services/api-gateway/src
      - ./services/api-gateway/test:/usr/src/app/services/api-gateway/test
      - ./services/api-gateway/@types:/usr/src/app/services/api-gateway/@types
      - ./libs/ts/common/src:/usr/src/app/libs/ts/common/src
      - ./libs/contracts/proto:/usr/src/app/libs/contracts/proto
      - type: bind
        source: ./services/api-gateway/tsconfig.json
        target: /usr/src/app/services/api-gateway/tsconfig.json
      - type: bind
        source: ./services/api-gateway/jest.config.ts
        target: /usr/src/app/services/api-gateway/jest.config.ts
    ports:
      - 3000:3000
    healthcheck:
      test: node ./healthcheck.js
      timeout: 10s
      start_period: 15s
    depends_on:
      learning-paths:
        condition: service_healthy
      progress:
        condition: service_healthy
