name: pathly-backend

include:
  - ./infra/auth/prod.compose.yaml
  - ./services/learning-paths/prod.compose.yaml
  - ./services/progress/prod.compose.yaml

services:
  reverse-proxy:
    build:
      context: ./infra/reverse-proxy
      target: prod
    env_file:
      - ./infra/reverse-proxy/.env.prod
    ports:
      - 4000:80
    depends_on:
      api-gateway:
        condition: service_healthy
      auth:
        restart: true
        condition: service_healthy
    restart: always
  api-gateway:
    build:
      context: .
      target: prod
      dockerfile: ./services/api-gateway/Dockerfile
    env_file:
      - ./services/api-gateway/.env.prod
    healthcheck:
      test: node ./healthcheck.js
      timeout: 10s
      start_period: 15s
    depends_on:
      learning-paths:
        condition: service_healthy
      progress:
        condition: service_healthy
