/**
 * @description This enum is collection of dependency injection tokens for nestjs. It's purpose is to keep them in one place to avoid using literals.
 */
export enum DiToken {
	PG_POOL = 'PG_POOL',
	DRIZZLE = 'DRIZZLE',

	FIND_PATHS_USE_CASE = 'FIND_PATHS_USE_CASE',
	FIND_ONE_PATH_USE_CASE = 'FIND_ONE_PATH_USE_CASE',
	CREATE_PATH_USE_CASE = 'CREATE_PATH_USE_CASE',
	UPDATE_PATH_USE_CASE = 'UPDATE_PATH_USE_CASE',
	REMOVE_PATH_USE_CASE = 'REMOVE_PATH_USE_CASE',

	FIND_SECTIONS_USE_CASE = 'FIND_SECTIONS_USE_CASE',
	FIND_ONE_SECTION_USE_CASE = 'FIND_ONE_SECTION_USE_CASE',
	CREATE_SECTION_USE_CASE = 'CREATE_SECTION_USE_CASE',
	UPDATE_SECTION_USE_CASE = 'UPDATE_SECTION_USE_CASE',
	REMOVE_SECTION_USE_CASE = 'REMOVE_SECTION_USE_CASE',
}
