export * from './activities.table';
export * from './articles.table';
export * from './exercises.table';
export * from './learning-paths.table';
export * from './lessons.table';
export * from './questions.table';
export * from './quizzes.table';
export * from './sections.table';
export * from './units.table';
