/**
 * @description This enum is collection of dependency injection tokens for nestjs. It's purpose is to keep them in one place to avoid using literals.
 */
export enum DiToken {
	PG_POOL = 'PG_POOL',
	DRIZZLE = 'DRIZZLE',

	LIST_LEARNING_PATHS_HANDLER = 'LIST_LEARNING_PATHS_HANDLER',
	FIND_LEARNING_PATH_BY_ID_HANDLER = 'FIND_LEARNING_PATH_BY_ID_HANDLER',
	CREATE_LEARNING_PATH_HANDLER = 'CREATE_LEARNING_PATH_HANDLER',
	UPDATE_LEARNING_PATH_HANDLER = 'UPDATE_LEARNING_PATH_HANDLER',
	REMOVE_LEARNING_PATH_HANDLER = 'REMOVE_LEARNING_PATH_HANDLER',

	LIST_SECTIONS_HANDLER = 'LIST_SECTIONS_HANDLER',
	FIND_SECTION_BY_ID_HANDLER = 'FIND_SECTION_BY_ID_HANDLER',
	ADD_SECTION_HANDLER = 'ADD_SECTION_HANDLER',
	UPDATE_SECTION_HANDLER = 'UPDATE_SECTION_HANDLER',
	REORDER_SECTION_HANDLER = 'REORDER_SECTION_HANDLER',
	REMOVE_SECTION_HANDLER = 'REMOVE_SECTION_HANDLER',

	LIST_UNITS_HANDLER = 'LIST_UNITS_HANDLER',
	FIND_UNIT_BY_ID_HANDLER = 'FIND_UNIT_BY_ID_HANDLER',
	ADD_UNIT_HANDLER = 'ADD_UNIT_HANDLER',
	UPDATE_UNIT_HANDLER = 'UPDATE_UNIT_HANDLER',
	REORDER_UNIT_HANDLER = 'REORDER_UNIT_HANDLER',
	REMOVE_UNIT_HANDLER = 'REMOVE_UNIT_HANDLER',

	LIST_LESSONS_HANDLER = 'LIST_LESSONS_HANDLER',
	FIND_LESSON_BY_ID_HANDLER = 'FIND_LESSON_BY_ID_HANDLER',
	ADD_LESSON_HANDLER = 'ADD_LESSON_HANDLER',
	UPDATE_LESSON_HANDLER = 'UPDATE_LESSON_HANDLER',
	REORDER_LESSON_HANDLER = 'REORDER_LESSON_HANDLER',
	REMOVE_LESSON_HANDLER = 'REMOVE_LESSON_HANDLER',

	LIST_ACTIVITIES_HANDLER = 'LIST_ACTIVITIES_HANDLER',
	LIST_ARTICLES_HANDLER = 'LIST_ARTICLES_HANDLER',
	LIST_EXERCISES_HANDLER = 'LIST_EXERCISES_HANDLER',
	LIST_QUIZZES_HANDLER = 'LIST_QUIZZES_HANDLER',
	FIND_ACTIVITY_BY_ID_HANDLER = 'FIND_ACTIVITY_BY_ID_HANDLER',
	REORDER_ACTIVITY_HANDLER = 'REORDER_ACTIVITY_HANDLER',
	REMOVE_ACTIVITY_HANDLER = 'REMOVE_ACTIVITY_HANDLER',

	FIND_ARTICLE_BY_ID_HANDLER = 'FIND_ARTICLE_BY_ID_HANDLER',
	ADD_ARTICLE_HANDLER = 'ADD_ARTICLE_HANDLER',
	UPDATE_ARTICLE_HANDLER = 'UPDATE_ARTICLE_HANDLER',

	FIND_EXERCISE_BY_ID_HANDLER = 'FIND_EXERCISE_BY_ID_HANDLER',
	ADD_EXERCISE_HANDLER = 'ADD_EXERCISE_HANDLER',
	UPDATE_EXERCISE_HANDLER = 'UPDATE_EXERCISE_HANDLER',

	FIND_QUIZ_BY_ID_HANDLER = 'FIND_QUIZ_BY_ID_HANDLER',
	ADD_QUIZ_HANDLER = 'ADD_QUIZ_HANDLER',
	UPDATE_QUIZ_HANDLER = 'UPDATE_QUIZ_HANDLER',

	FIND_QUESTION_BY_ID_HANDLER = 'FIND_QUESTION_BY_ID_HANDLER',
	ADD_QUESTION_HANDLER = 'ADD_QUESTION_HANDLER',
	UPDATE_QUESTION_HANDLER = 'UPDATE_QUESTION_HANDLER',
	REORDER_QUESTION_HANDLER = 'REORDER_QUESTION_HANDLER',
	REMOVE_QUESTION_HANDLER = 'REMOVE_QUESTION_HANDLER',

	START_LEARNING_PATH_HANDLER = 'START_LEARNING_PATH_HANDLER',
	REMOVE_LEARNING_PATH_PROGRESS_HANDLER = 'REMOVE_LEARNING_PATH_PROGRESS_HANDLER',
	LIST_LEARNING_PATH_PROGRESS_HANDLER = 'LIST_LEARNING_PATH_PROGRESS_HANDLER',
	FIND_LEARNING_PATH_PROGRESS_FOR_USER_HANDLER = 'FIND_LEARNING_PATH_PROGRESS_FOR_USER_HANDLER',

	START_SECTION_HANDLER = 'START_SECTION_HANDLER',
	REMOVE_SECTION_PROGRESS_HANDLER = 'REMOVE_SECTION_PROGRESS_HANDLER',
	LIST_SECTION_PROGRESS_HANDLER = 'LIST_SECTION_PROGRESS_HANDLER',
	FIND_SECTION_PROGRESS_FOR_USER_HANDLER = 'FIND_SECTION_PROGRESS_FOR_USER_HANDLER',

	START_UNIT_HANDLER = 'START_UNIT_HANDLER',
	REMOVE_UNIT_PROGRESS_HANDLER = 'REMOVE_UNIT_PROGRESS_HANDLER',
	LIST_UNIT_PROGRESS_HANDLER = 'LIST_UNIT_PROGRESS_HANDLER',
	FIND_UNIT_PROGRESS_FOR_USER_HANDLER = 'FIND_UNIT_PROGRESS_FOR_USER_HANDLER',

	START_LESSON_HANDLER = 'START_LESSON_HANDLER',
	REMOVE_LESSON_PROGRESS_HANDLER = 'REMOVE_LESSON_PROGRESS_HANDLER',
	LIST_LESSON_PROGRESS_HANDLER = 'LIST_LESSON_PROGRESS_HANDLER',
	FIND_LESSON_PROGRESS_FOR_USER_HANDLER = 'FIND_LESSON_PROGRESS_FOR_USER_HANDLER',

	COMPLETE_ACTIVITY_HANDLER = 'COMPLETE_ACTIVITY_HANDLER',
	REMOVE_ACTIVITY_PROGRESS_HANDLER = 'REMOVE_ACTIVITY_PROGRESS_HANDLER',
	LIST_ACTIVITY_PROGRESS_HANDLER = 'LIST_ACTIVITY_PROGRESS_HANDLER',
	FIND_ACTIVITY_PROGRESS_FOR_USER_HANDLER = 'FIND_ACTIVITY_PROGRESS_FOR_USER_HANDLER',

	ON_ACTIVITY_COMPLETED_HANDLER = 'ON_ACTIVITY_COMPLETED_HANDLER',
	ON_LESSON_COMPLETED_HANDLER = 'ON_LESSON_COMPLETED_HANDLER',
	ON_UNIT_COMPLETED_HANDLER = 'ON_UNIT_COMPLETED_HANDLER',
	ON_SECTION_COMPLETED_HANDLER = 'ON_SECTION_COMPLETED_HANDLER',
	ON_LEARNING_PATH_COMPLETED_HANDLER = 'ON_LEARNING_PATH_COMPLETED_HANDLER',

	NEO4J_DRIVER = 'NEO4J_DRIVER',

	CREATE_SKILL_HANDLER = 'CREATE_SKILL_HANDLER',
	UPDATE_SKILL_HANDLER = 'UPDATE_SKILL_HANDLER',
	REMOVE_SKILL_HANDLER = 'REMOVE_SKILL_HANDLER',

	ADD_NEXT_STEP_SKILL_HANDLER = 'ADD_NEXT_STEP_SKILL_HANDLER',
	ADD_CHILD_SKILL_HANDLER = 'ADD_CHILD_SKILL_HANDLER',

	FIND_SKILL_BY_ID_HANDLER = 'FIND_SKILL_BY_ID_HANDLER',
	FIND_SKILL_BY_SLUG_HANDLER = 'FIND_SKILL_BY_SLUG_HANDLER',
	LIST_SKILL_CHILDREN_HANDLER = 'LIST_SKILL_CHILDREN_HANDLER',
	LIST_SKILL_PREREQUISITIES_HANDLER = 'LIST_SKILL_PREREQUISITIES_HANDLER',
	LIST_SKILL_NEXT_STEPS_HANDLER = 'LIST_SKILL_NEXT_STEPS_HANDLER',
	GET_PREREQUISITE_GRAPH_HANDLER = 'GET_PREREQUISITE_GRAPH_HANDLER',

	SKILL_GRAPH_SERVICE = 'SKILL_GRAPH_SERVICE',
	SKILL_PROGRESS_SERVICE = 'SKILL_PROGRESS_SERVICE',

	UNLOCK_SKILL_HANDLER = 'UNLOCK_SKILL_HANDLER',
	LIST_SKILL_PROGRESS_FOR_USER_HANDLER = 'LIST_SKILL_PROGRESS_FOR_USER_HANDLER',
	FIND_ONE_SKILL_PROGRESS_FOR_USER_HANDLER = 'FIND_ONE_SKILL_PROGRESS_FOR_USER_HANDLER',
}
