export enum DiToken {
	PG_POOL = 'PG_POOL',
	DRIZZLE = 'DRIZZLE',

	LEARNING_PATHS_PACKAGE = 'LEARNING_PATHS_PACKAGE',

	COMPLETE_ACTIVITY_USE_CASE = 'COMPLETE_ACTIVITY_USE_CASE',
	START_ACTIVITY_USE_CASE = 'START_ACTIVITY_USE_CASE',
	FIND_ONE_ACTIVITY_PROGRESS_USE_CASE = 'FIND_ONE_ACTIVITY_PROGRESS_USE_CASE',
	FIND_ACTIVITY_PROGRESS_BY_ID_USE_CASE = 'FIND_ACTIVITY_PROGRESS_BY_ID_USE_CASE',
	REMOVE_ACTIVITY_PROGRESS_BY_ID_USE_CASE = 'REMOVE_ACTIVITY_PROGRESS_BY_ID_USE_CASE',
	LIST_ACTIVITY_PROGRESS_USE_CASE = 'LIST_ACTIVITY_PROGRESS_USE_CASE',

	START_LESSON_USE_CASE = 'START_LESSON_USE_CASE',
	FIND_ONE_LESSON_PROGRESS_FOR_USER_USE_CASE = 'FIND_ONE_LESSON_PROGRESS_FOR_USER_USE_CASE',
	FIND_LESSON_PROGRESS_BY_ID_USE_CASE = 'FIND_LESSON_PROGRESS_BY_ID_USE_CASE',
	REMOVE_LESSON_PROGRESS_BY_ID_USE_CASE = 'REMOVE_LESSON_PROGRESS_BY_ID_USE_CASE',
	LIST_LESSON_PROGRESS_USE_CASE = 'LIST_LESSON_PROGRESS_USE_CASE',

	ON_ACTIVITY_COMPLETED_HANDLER = 'ON_ACTIVITY_COMPLETED_HANDLER',
	ON_LESSON_COMPLETED_HANDLER = 'ON_LESSON_COMPLETED_HANDLER',
}
