export enum DiToken {
	PG_POOL = 'PG_POOL',
	DRIZZLE = 'DRIZZLE',

	LEARNING_PATHS_PACKAGE = 'LEARNING_PATHS_PACKAGE',

	COMPLETE_ACTIVITY_HANDLER = 'COMPLETE_ACTIVITY_HANDLER',
	REMOVE_ACTIVITY_PROGRESS_HANDLER = 'REMOVE_ACTIVITY_PROGRESS_HANDLER',
	LIST_ACTIVITY_PROGRESS_HANDLER = 'LIST_ACTIVITY_PROGRESS_HANDLER',
	FIND_ACTIVITY_PROGRESS_FOR_USER_HANDLER = 'FIND_ACTIVITY_PROGRESS_FOR_USER_HANDLER',
	FIND_ACTIVITY_PROGRESS_BY_ID_HANDLER = 'FIND_ACTIVITY_PROGRESS_BY_ID_HANDLER',

	START_LESSON_HANDLER = 'START_LESSON_HANDLER',
	REMOVE_LESSON_PROGRESS_HANDLER = 'REMOVE_LESSON_PROGRESS_HANDLER',
	LIST_LESSON_PROGRESS_HANDLER = 'LIST_LESSON_PROGRESS_HANDLER',
	FIND_LESSON_PROGRESS_FOR_USER_HANDLER = 'FIND_LESSON_PROGRESS_FOR_USER_HANDLER',
	FIND_LESSON_PROGRESS_BY_ID_HANDLER = 'FIND_LESSON_PROGRESS_BY_ID_HANDLER',

	START_UNIT_HANDLER = 'START_UNIT_HANDLER',
	REMOVE_UNIT_PROGRESS_HANDLER = 'REMOVE_UNIT_PROGRESS_HANDLER',
	LIST_UNIT_PROGRESS_HANDLER = 'LIST_UNIT_PROGRESS_HANDLER',
	FIND_UNIT_PROGRESS_FOR_USER_HANDLER = 'FIND_UNIT_PROGRESS_FOR_USER_HANDLER',
	FIND_UNIT_PROGRESS_BY_ID_HANDLER = 'FIND_UNIT_PROGRESS_BY_ID_HANDLER',

	START_SECTION_HANDLER = 'START_SECTION_HANDLER',
	REMOVE_SECTION_PROGRESS_HANDLER = 'REMOVE_SECTION_PROGRESS_HANDLER',
	LIST_SECTION_PROGRESS_HANDLER = 'LIST_SECTION_PROGRESS_HANDLER',
	FIND_SECTION_PROGRESS_FOR_USER_HANDLER = 'FIND_SECTION_PROGRESS_FOR_USER_HANDLER',
	FIND_SECTION_PROGRESS_BY_ID_HANDLER = 'FIND_SECTION_PROGRESS_BY_ID_HANDLER',

	START_LEARNING_PATH_HANDLER = 'START_LEARNING_PATH_HANDLER',
	REMOVE_LEARNING_PATH_PROGRESS_HANDLER = 'REMOVE_LEARNING_PATH_PROGRESS_HANDLER',
	LIST_LEARNING_PATH_PROGRESS_HANDLER = 'LIST_LEARNING_PATH_PROGRESS_HANDLER',
	FIND_LEARNING_PATH_PROGRESS_FOR_USER_HANDLER = 'FIND_LEARNING_PATH_PROGRESS_FOR_USER_HANDLER',
	FIND_LEARNING_PATH_PROGRESS_BY_ID_HANDLER = 'FIND_LEARNING_PATH_PROGRESS_BY_ID_HANDLER',

	ON_ACTIVITY_COMPLETED_HANDLER = 'ON_ACTIVITY_COMPLETED_HANDLER',
	ON_LESSON_COMPLETED_HANDLER = 'ON_LESSON_COMPLETED_HANDLER',
	ON_UNIT_COMPLETED_HANDLER = 'ON_UNIT_COMPLETED_HANDLER',
	ON_SECTION_COMPLETED_HANDLER = 'ON_SECTION_COMPLETED_HANDLER',
	ON_LEARNING_PATH_COMPLETED_HANDLER = 'ON_LEARNING_PATH_COMPLETED_HANDLER',
}
