CREATE (theBasics:Skill {name: 'the-basics'})
CREATE (webDev:Skill {name: 'web-dev'})
CREATE (ai:Skill {name: 'ai'})
CREATE (mobileDev:Skill {name: 'mobile-dev'})
CREATE (gameDev:Skill {name: 'game-dev'})
CREATE (theBasics)-[:PREREQUISITE_OF]->(webDev)
CREATE (theBasics)-[:PREREQUISITE_OF]->(ai)
CREATE (theBasics)-[:PREREQUISITE_OF]->(mobileDev)
CREATE (theBasics)-[:PREREQUISITE_OF]->(gameDev)