services:
  graph-db:
    image: neo4j:latest
    volumes:
      - graph-db-data:/data
    environment:
      - NEO4J_AUTH=neo4j/zaq1@WSX
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p zaq1@WSX 'RETURN 1;'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
volumes:
  graph-db-data: