export enum DiToken {
	NEO4J_DRIVER = 'NEO4J_DRIVER',

	CREATE_SKILL_HANDLER = 'CREATE_SKILL_HANDLER',
	UPDATE_SKILL_HANDLER = 'UPDATE_SKILL_HANDLER',
	REMOVE_SKILL_HANDLER = 'REMOVE_SKILL_HANDLER',

	ADD_PREREQUISITE_SKILL_HANDLER = 'ADD_PREREQUISITE_SKILL_HANDLER',
	ADD_CHILD_SKILL_HANDLER = 'ADD_CHILD_SKILL_HANDLER',
	ADD_COMMON_SKILL_HANDLER = 'ADD_COMMON_SKILL_HANDLER',
	ADD_ALTERNATIVE_SKILL_HANDLER = 'ADD_ALTERNATIVE_SKILL_HANDLER',

	FIND_SKILL_BY_ID_HANDLER = 'FIND_SKILL_BY_ID_HANDLER',
	FIND_SKILL_BY_SLUG_HANDLER = 'FIND_SKILL_BY_SLUG_HANDLER',
	LIST_SKILL_ALTERNATIVES_HANDLER = 'LIST_SKILL_ALTERNATIVES_HANDLER',
	LIST_SKILL_CHILDREN_HANDLER = 'LIST_SKILL_CHILDREN_HANDLER',
	LIST_COMMON_SKILLS_HANDLER = 'LIST_COMMON_SKILLS_HANDLER',
	LIST_SKILL_PREREQUISITIES_HANDLER = 'LIST_SKILL_PREREQUISITIES_HANDLER',
	GET_TOP_LEVEL_PREREQUISITE_GRAPH_HANDLER = 'GET_TOP_LEVEL_PREREQUISITE_GRAPH_HANDLER',

	SKILL_GRAPH_SERVICE = 'SKILL_GRAPH_SERVICE',
}
