export enum DiToken {
	NEO4J_DRIVER = 'NEO4J_DRIVER',

	CREATE_SKILL_HANDLER = 'CREATE_SKILL_HANDLER',
	UPDATE_SKILL_HANDLER = 'UPDATE_SKILL_HANDLER',
	REMOVE_SKILL_HANDLER = 'REMOVE_SKILL_HANDLER',

	ADD_NEXT_STEP_SKILL_HANDLER = 'ADD_NEXT_STEP_SKILL_HANDLER',
	ADD_CHILD_SKILL_HANDLER = 'ADD_CHILD_SKILL_HANDLER',

	FIND_SKILL_BY_ID_HANDLER = 'FIND_SKILL_BY_ID_HANDLER',
	FIND_SKILL_BY_SLUG_HANDLER = 'FIND_SKILL_BY_SLUG_HANDLER',
	LIST_SKILL_CHILDREN_HANDLER = 'LIST_SKILL_CHILDREN_HANDLER',
	LIST_SKILL_PREREQUISITIES_HANDLER = 'LIST_SKILL_PREREQUISITIES_HANDLER',
	LIST_SKILL_NEXT_STEPS_HANDLER = 'LIST_SKILL_NEXT_STEPS_HANDLER',
	GET_PREREQUISITE_GRAPH_HANDLER = 'GET_PREREQUISITE_GRAPH_HANDLER',

	SKILL_GRAPH_SERVICE = 'SKILL_GRAPH_SERVICE',
	SKILL_PROGRESS_SERVICE = 'SKILL_PROGRESS_SERVICE',

	UNLOCK_SKILL_HANDLER = 'UNLOCK_SKILL_HANDLER',
	FIND_SKILL_PROGRESS_FOR_USER_HANDLER = 'FIND_SKILL_PROGRESS_FOR_USER_HANDLER',
	FIND_ONE_SKILL_PROGRESS_FOR_USER_HANDLER = 'FIND_ONE_SKILL_PROGRESS_FOR_USER_HANDLER',
}
