services:
  auth:
    build:
      context: .
      target: dev
    env_file:
      - .env
    healthcheck:
      test:
        - CMD-SHELL
        - > 
          bash -c '
            exec 3<>/dev/tcp/localhost/9000;
            printf "GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3;
            read -r data <&3;
            status=$${data:8:4};
            [ "$$status" -lt 400 ]
          '
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 20s
    ports:
      - 8080:8080
  auth-db:
    build:
      context: ./db
    env_file:
      - ./db/.env
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      timeout: 30s
      retries: 5
      start_period: 20s
volumes:
  auth-db-data: