/**
 * @description This enum is collection of dependency injection tokens for nestjs. It's purpose is to keep them in one place to avoid using literals.
 */
export enum DiToken {
	PG_POOL = 'PG_POOL',
	DRIZZLE = 'DRIZZLE',

	LIST_LEARNING_PATHS_HANDLER = 'LIST_LEARNING_PATHS_HANDLER',
	FIND_LEARNING_PATH_BY_ID_HANDLER = 'FIND_LEARNING_PATH_BY_ID_HANDLER',
	CREATE_LEARNING_PATH_HANDLER = 'CREATE_LEARNING_PATH_HANDLER',
	UPDATE_LEARNING_PATH_HANDLER = 'UPDATE_LEARNING_PATH_HANDLER',
	REMOVE_LEARNING_PATH_HANDLER = 'REMOVE_LEARNING_PATH_HANDLER',

	LIST_SECTIONS_HANDLER = 'LIST_SECTIONS_HANDLER',
	FIND_SECTION_BY_ID_HANDLER = 'FIND_SECTION_BY_ID_HANDLER',
	ADD_SECTION_HANDLER = 'ADD_SECTION_HANDLER',
	UPDATE_SECTION_HANDLER = 'UPDATE_SECTION_HANDLER',
	REORDER_SECTION_HANDLER = 'REORDER_SECTION_HANDLER',
	REMOVE_SECTION_HANDLER = 'REMOVE_SECTION_HANDLER',

	LIST_UNITS_HANDLER = 'LIST_UNITS_HANDLER',
	FIND_UNIT_BY_ID_HANDLER = 'FIND_UNIT_BY_ID_HANDLER',
	ADD_UNIT_HANDLER = 'ADD_UNIT_HANDLER',
	UPDATE_UNIT_HANDLER = 'UPDATE_UNIT_HANDLER',
	REORDER_UNIT_HANDLER = 'REORDER_UNIT_HANDLER',
	REMOVE_UNIT_HANDLER = 'REMOVE_UNIT_HANDLER',

	LIST_LESSONS_HANDLER = 'LIST_LESSONS_HANDLER',
	FIND_LESSON_BY_ID_HANDLER = 'FIND_LESSON_BY_ID_HANDLER',
	ADD_LESSON_HANDLER = 'ADD_LESSON_HANDLER',
	UPDATE_LESSON_HANDLER = 'UPDATE_LESSON_HANDLER',
	REORDER_LESSON_HANDLER = 'REORDER_LESSON_HANDLER',
	REMOVE_LESSON_HANDLER = 'REMOVE_LESSON_HANDLER',

	LIST_ACTIVITIES_HANDLER = 'LIST_ACTIVITIES_HANDLER',
	LIST_ARTICLES_HANDLER = 'LIST_ARTICLES_HANDLER',
	LIST_EXERCISES_HANDLER = 'LIST_EXERCISES_HANDLER',
	LIST_QUIZZES_HANDLER = 'LIST_QUIZZES_HANDLER',
	FIND_ACTIVITY_BY_ID_HANDLER = 'FIND_ACTIVITY_BY_ID_HANDLER',
	REORDER_ACTIVITY_HANDLER = 'REORDER_ACTIVITY_HANDLER',
	REMOVE_ACTIVITY_HANDLER = 'REMOVE_ACTIVITY_HANDLER',

	FIND_ARTICLE_BY_ID_HANDLER = 'FIND_ARTICLE_BY_ID_HANDLER',
	ADD_ARTICLE_HANDLER = 'ADD_ARTICLE_HANDLER',
	UPDATE_ARTICLE_HANDLER = 'UPDATE_ARTICLE_HANDLER',

	FIND_EXERCISE_BY_ID_HANDLER = 'FIND_EXERCISE_BY_ID_HANDLER',
	ADD_EXERCISE_HANDLER = 'ADD_EXERCISE_HANDLER',
	UPDATE_EXERCISE_HANDLER = 'UPDATE_EXERCISE_HANDLER',

	FIND_QUIZ_BY_ID_HANDLER = 'FIND_QUIZ_BY_ID_HANDLER',
	ADD_QUIZ_HANDLER = 'ADD_QUIZ_HANDLER',
	UPDATE_QUIZ_HANDLER = 'UPDATE_QUIZ_HANDLER',

	FIND_QUESTION_BY_ID_HANDLER = 'FIND_QUESTION_BY_ID_HANDLER',
	ADD_QUESTION_HANDLER = 'ADD_QUESTION_HANDLER',
	UPDATE_QUESTION_HANDLER = 'UPDATE_QUESTION_HANDLER',
	REORDER_QUESTION_HANDLER = 'REORDER_QUESTION_HANDLER',
	REMOVE_QUESTION_HANDLER = 'REMOVE_QUESTION_HANDLER',
}
