/**
 * @description This enum is collection of dependency injection tokens for nestjs. It's purpose is to keep them in one place to avoid using literals.
 */
export enum DiToken {
	PG_POOL = 'PG_POOL',
	DRIZZLE = 'DRIZZLE',

	FIND_LEARNING_PATHS_USE_CASE = 'FIND_LEARNING_PATHS_USE_CASE',
	FIND_ONE_LEARNING_PATH_USE_CASE = 'FIND_ONE_LEARNING_PATH_USE_CASE',
	CREATE_LEARNING_PATH_USE_CASE = 'CREATE_LEARNING_PATH_USE_CASE',
	UPDATE_LEARNING_PATH_USE_CASE = 'UPDATE_LEARNING_PATH_USE_CASE',
	REMOVE_LEARNING_PATH_USE_CASE = 'REMOVE_LEARNING_PATH_USE_CASE',

	FIND_SECTIONS_USE_CASE = 'FIND_SECTIONS_USE_CASE',
	FIND_ONE_SECTION_USE_CASE = 'FIND_ONE_SECTION_USE_CASE',
	CREATE_SECTION_USE_CASE = 'CREATE_SECTION_USE_CASE',
	UPDATE_SECTION_USE_CASE = 'UPDATE_SECTION_USE_CASE',
	REMOVE_SECTION_USE_CASE = 'REMOVE_SECTION_USE_CASE',

	FIND_UNITS_USE_CASE = 'FIND_UNITS_USE_CASE',
	FIND_ONE_UNIT_USE_CASE = 'FIND_ONE_UNIT_USE_CASE',
	CREATE_UNIT_USE_CASE = 'CREATE_UNIT_USE_CASE',
	UPDATE_UNIT_USE_CASE = 'UPDATE_UNIT_USE_CASE',
	REMOVE_UNIT_USE_CASE = 'REMOVE_UNIT_USE_CASE',

	FIND_LESSONS_USE_CASE = 'FIND_LESSONS_USE_CASE',
	FIND_ONE_LESSON_USE_CASE = 'FIND_ONE_LESSON_USE_CASE',
	CREATE_LESSON_USE_CASE = 'CREATE_LESSON_USE_CASE',
	UPDATE_LESSON_USE_CASE = 'UPDATE_LESSON_USE_CASE',
	REMOVE_LESSON_USE_CASE = 'REMOVE_LESSON_USE_CASE',
}
