export enum DiToken {
	LEARNING_PATHS_PACKAGE = 'LEARNING_PATHS_PACKAGE',
	SECTIONS_PACKAGE = 'SECTIONS_PACKAGE',
	UNITS_PACKAGE = 'UNITS_PACKAGE',
	LESSONS_PACKAGE = 'LESSONS_PACKAGE',
	ACTIVITIES_PACKAGE = 'ACTIVITIES_PACKAGE',

	ACTIVITY_PROGRESS_PACKAGE = 'ACTIVITY_PROGRESS_PACKAGE',
}
