services:
  paths:
    build:
      context: ../../
      target: dev
      dockerfile: ./services/paths/Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/services/paths/src
      - ./test:/usr/src/app/services/paths/test
      - ../../libs/ts/common/src:/usr/src/app/libs/ts/common/src
      - ../../libs/contracts/proto:/usr/src/app/libs/contracts/proto
    depends_on:
      paths-db:
        condition: service_healthy
    healthcheck:
      test: node ./healthcheck.js
      timeout: 10s
      start_period: 15s
    ports:
      - 3002:5000

  paths-db:
    build:
      context: ./db
    env_file:
      - ./db/.env
    volumes:
      - paths-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      timeout: 30s
      retries: 5
      start_period: 20s

volumes:
  paths-db-data:
