services:
  paths:
    build:
      context: ../../
      target: prod
      dockerfile: ./services/paths/Dockerfile
    env_file:
      - .env.prod
    depends_on:
      paths-db:
        condition: service_healthy
    healthcheck:
      test: grpc_health_probe -addr=localhost:3000
      timeout: 10s
      start_period: 15s

  paths-db:
    build:
      context: ./db
    env_file:
      - ./db/.env.prod
    volumes:
      - paths-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      timeout: 30s
      retries: 5
      start_period: 20s

volumes:
  paths-db-data:
